# optional domain to listen on
domain: prod.example.com
# optional version string
version: 1.0
# runtime (ruby, python, php, java)
runtime: cannula.runtime.Python
api_version: 1

# setup some defaults to pass to handlers
gunicorn_defaults: 
  workers: 2
  worker-class: sync
  worker-connections: 1000
  max_requests: 0
  timeout: 30
  keepalive: 2
  
# Main wsgi handlers and static file definitions
# Each unique 'worker' handler will setup a separate process
handlers:
# static files (less greedy urls should come first!)
- url: /static
  static_dir: path/to/static/folder

- url: /admin
  worker: cannula.worker.gunicorn
  script: admin.py
  secure: true
  defaults: gunicorn_defaults

# Main site handler will match everything else
- url: /
  worker: cannula.worker.gunicorn_django
  settings: myproject.settings
  defaults: gunicorn_defaults